version: '3.9'

services:
  web:
    build: .
    ports:
      - "8088:8088"
    environment:
      DB_NAME: chat
      DB_USER: user 
      DB_PASSWORD: user_password
      DB_SHARDS: '[{"host":"db-node-1","port":3306}, {"host":"db-node-2", "port":3306}]'
    volumes:
      - .:/code
    links:
      - db-node-1
      - db-node-2
  db-node-1:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: chat
      MYSQL_USER: user 
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
  db-node-2:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: chat
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3307:3306"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
